[package]
name = "day-13"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.2"
gcd = "2.3.0"
good_lp = "1.10.0"
itertools = "0.13.0"
mathru = "0.15.4"
regex = "1.11.1"
